# Generated by Django 2.2.5 on 2020-03-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('paid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50)),
                ('amount', models.IntegerField()),
                ('unique_number', models.IntegerField(primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('leads_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Leads')),
            ],
        ),
    ]
