# Generated by Django 3.0.2 on 2020-02-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50)),
                ('amount', models.IntegerField()),
                ('unique_number', models.CharField(max_length=15)),
                ('leads_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Leads')),
            ],
        ),
    ]
