# Generated by Django 3.0.2 on 2020-02-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='unique_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
