# Generated by Django 2.2.5 on 2020-03-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200213_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
