# Generated by Django 3.0.3 on 2020-02-29 14:53

from django.db import migrations, models
import venus.models


class Migration(migrations.Migration):

    dependencies = [
        ('venus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venus',
            name='venu_image',
            field=models.ImageField(blank=True, null=True, upload_to=venus.models.upload_files),
        ),
    ]
