# Generated by Django 3.0.2 on 2020-02-13 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('company_type', models.CharField(choices=[('SO', 'Ship-owners'), ('SY', 'Shipyards'), ('PR', 'Ports'), ('EP', 'Eqipments Provider')], default='SO', max_length=50)),
                ('user_type', models.CharField(choices=[('Panelist', 'Panelist'), ('Delegate', 'Delegate'), ('Exhibitor', 'Exhibitor'), ('Speaker', 'Speaker')], default='Panelist', max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('terms', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
