# Generated by Django 2.2.5 on 2020-03-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='agreement_number',
            field=models.IntegerField(null=True),
        ),
    ]
