# Generated by Django 2.2.5 on 2020-03-08 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('acceptance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('meeting_description', models.CharField(max_length=300)),
                ('meeting_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_from', to=settings.AUTH_USER_MODEL)),
                ('meeting_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
